"""ai upgrade: new columns and tables

Revision ID: 932f89933323
Revises: 2ed2a050e204
Create Date: 2026-08-29 22:36:02.330988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932f89933323'
down_revision = '2ed2a050e204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_colors', sa.Text(), nullable=True),
    sa.Column('preferred_styles', sa.Text(), nullable=True),
    sa.Column('preferred_occasions', sa.Text(), nullable=True),
    sa.Column('preferred_seasons', sa.Text(), nullable=True),
    sa.Column('disliked_colors', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('outfit_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outfit_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfit_feedback_outfit_id'), ['outfit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outfit_feedback_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('clothing_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('clothing_type', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('detected_color_hex', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('ai_confidence', sa.Float(), nullable=True))

    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compatibility_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('recommendation_type', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.drop_column('recommendation_type')
        batch_op.drop_column('compatibility_score')

    with op.batch_alter_table('clothing_items', schema=None) as batch_op:
        batch_op.drop_column('ai_confidence')
        batch_op.drop_column('detected_color_hex')
        batch_op.drop_column('clothing_type')
        batch_op.drop_column('style')

    with op.batch_alter_table('outfit_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfit_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_outfit_feedback_outfit_id'))

    op.drop_table('outfit_feedback')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))

    op.drop_table('user_preferences')
    # ### end Alembic commands ###
