"""Add admin flag to User

Revision ID: d54c1420073c
Revises: f1a2b3c4d5e6
Create Date: 2026-09-21 08:30:18.643767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54c1420073c'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the is_admin column as nullable with a server default for SQLite compatibility.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True, server_default=sa.text('0')))

    # Back‑fill existing rows to ensure a concrete value (False/0).
    op.execute("UPDATE users SET is_admin = 0")

    # Now make the column non‑nullable and drop the default.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin', existing_type=sa.Boolean(), nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
